### ISSUE TITLE
Instagram embedded videos don't work in Edge

### ISSUE THREAD

**Issue by jordanmills** [s9e/xenforo-ext-media-sites#1]
Tested across a few profiles/computers.  Works fine in IE, but not Edge.  It's in the insta iframe so it might be out of your control, but they may have a better embed frame to use.

The root issue is the stylesheet EmbedSimpleBase.css rule for “#react-root, article, div, footer, header, main, nav, section” setting “position” to “relative”.  It works if that is removed or set to “static”.  It works as-is in IE, and from looking at it I think it's an issue with Edge mis-prioritizing stylesheets - the behavior is the same even if I set a higher level style without or with !important.

Tested on Edge 41.16299.402.0 (among others) and IE 11.431.16299.0.

**Comment by JoshyPHP** [comment]
As you suspected, CSS issues such as those are outside of my control. I looked at Instagram's latest embed script and they use the same iframe as I do.

If you contact Instagram about the CSS conflicts I think they'll be happy to receive your feedback and fix the issue if possible.

Finally, I don't have a Windows machine but I tried to loading [this page](https://s9e.github.io/iframe/2/instagram.min.html#gbGaIXBQbn) via a [Sauce Labs](https://saucelabs.com/) instance and it appeared fine on IE 11. Do you have a public page that shows an Instagram video that misbehaves on IE 11? Either way it won't help fixing this issue but I'd be interested in seeing it in action.

**Comment by jordanmills** [comment]
It works fine in IE, but not Edge.  That link under "this page" shows the same issue.  I can set you up with a throwaway VM in Azure for a day or two if you want to see it in action (email jordan at jordan mills dot com if you want me to set that up - I don't want to post connection info in a public thread).

**Comment by JoshyPHP** [comment]
Sorry, I meant Edge 18 and got mixed up. Sauce Labs doesn't seem to have any of the Blink-based Edge.

No need for a test page, I don't have access to the Blink Edge anyway. At this point, your best bet is to fire an email to Instagram, see if they can reproduce and fix it.
