### ISSUE TITLE
Youtube Community feed and posts shows as external link only

### ISSUE THREAD

**Issue by Bugaga13** [s9e/xenforo-ext-media-sites#14]
When we add a regular video, it's OK.

But when we add https://www.youtube.com/@Channel_link/community, then embed or iframe does not occur. It just turns out to be an external link.
The same with http://youtube.com/post/link

**Comment by JoshyPHP** [comment]
It works as expected. AFAIK YouTube doesn't provide a way to embed a community page or a post.
